### ISSUE TITLE
Change from Majority vote system

### ISSUE THREAD

**Issue by Carl-71** [MetoolDaddy/hammertime#3]
With the change from public to sentinel voting taken up in issue 2. 
Rather than a majority vote would it be more valuable to accept the sentinel call vote + one other sentinel yes as a valid reason to allow kick/ban.
Rather than a minority vote would it be more valuable to accept the sentinel call vote + no other sentinel yes as a valid reason to not allow kick/ban.

As we are looking at sentinels making the vote and they are picked as trusted players who will make the right call. This may work better as we may not always have 3 or 4 sentinels online to create a majority.

This is more of a suggestion than issue, not sure if it could work with the code you have.

**Comment by MetoolDaddy** [comment]
I don't quite get the point. Like, at all.

**Comment by blockbandit** [comment]
The program does not keep track of which sentinels are online. It tallies votes received when sentinels explicitly vote yes or no. It then calculates which is majority. I understand your suggestion Carl but it cannot be implemented in the current form of the software, as far as I know

**Comment by yer-mtd** [comment]
Exactly as stated by previous comment, with an additoon :

An AFK "sentinel" results in a ruined day.

Issue is closed.
